cal/urls.py
from django.urls import path,include
from . import views

app_name = 'cal'
urlpatterns = [
    path('', views.CalendarView.as_view(), name='calendar'),
    path('index/', views.index, name='index'),
    path('calendar/', views.CalendarView.as_view(), name='calendar'),
    path('event/new/', views.event, name='event_new'),
	path('event/edit/(?P<event_id>\d+)/', views.eventView, name='event_edit'),
    path('event/edit/new/', views.eventDelete, name='event_delete'),
    
    path("login/", views.login_request, name="login"),
    path("register/", views.register_request, name="register"),
    path("logout/", views.logout_request, name= "logout"),
    path("setPasswd/", views.setPasswd, name= "setPasswd"),
    path("updatePasswd/", views.updatePasswd, name= "updatePasswd")
#    path('test/', views.test, name='test'),
]

djangocalendar/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cal.urls')),
]

cal/models.py
from django.db import models
from django.urls import reverse
from django import forms



class Event(models.Model):
    Users = models.CharField(max_length=100,null=True)#搞成一个下拉框，选择人名字
    description = models.CharField(max_length=100)#
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

    @property
    def get_html_url(self):
        url = reverse('cal:event_edit', args=(self.id,))
        return f'<a href="{url}"> {self.Users} </a>'+"\n"+str(self.start_time.strftime("%H:%M"))+"~"+str(self.end_time.strftime("%H:%M"))
        
    def __str__(self):
        return self.Users

        
class Users(models.Model):
    Users = models.CharField(max_length=100,null=True)#搞成一个下拉框，选择人名字
    description = models.CharField(max_length=100)#
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()

    @property
    def get_html_url(self):
        url = reverse('cal:event_edit', args=(self.id,))
        return f'<a href="{url}"> {self.Users} </a>'
        
    def __str__(self):
        return self.Users

cal/forms.py
from django.forms import ModelForm, DateInput,Select,PasswordInput,ChoiceField,ModelChoiceField
from cal.models import Event
from datetime import datetime
from django import forms



class EventForm(ModelForm):
#  title = forms.ChoiceField(choices=USER_NMAE)
  class Meta:
    model = Event
    # datetime-local is a HTML5 input type, format to make date time show on fields
    widgets = {
      'start_time': DateInput(attrs={'type': 'datetime-local','value': datetime.now().strftime("%d-%m-%Y")}, format='%Y-%m-%dT%H:%M'),
      'end_time': DateInput(attrs={'type': 'datetime-local','value': datetime.now().strftime("%d-%m-%Y")}, format='%Y-%m-%dT%H:%M')
    }
    fields = '__all__'


  def __init__(self, *args, **kwargs):
    super(EventForm, self).__init__(*args, **kwargs)
    # input_formats parses HTML5 datetime-local input to datetime field
    self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
    self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)
    #users = Event.objects.all()
    #self.fields['Users']=forms.ModelChoiceField(queryset = Event.objects.all())
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

    #注释信息
	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

    #类的方法：保存数据
	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user 

cal/views.py
from datetime import datetime, timedelta, date
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.views import generic
from django.urls import reverse
from django.utils.safestring import mark_safe
import calendar

from .models import *
from .utils import Calendar
from .forms import EventForm
#from .forms import ExampleForm

def index(request):
    return HttpResponse('hello')

class CalendarView(generic.ListView):
    model = Event
    template_name = 'cal/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get('month', None))
        cal = Calendar(d.year, d.month)
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)#将这个返回值，布局到ui界面
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        context['footer'] = mark_safe("<a href='#'>首页</a>")
        return context

def get_date(req_month):
    if req_month:
        year, month = (int(x) for x in req_month.split('-'))
        return date(year, month, day=1)
    return datetime.today()

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month
    
        
def event(request, event_id=None):
    if request.user.is_authenticated:
        instance = Event()
        if event_id:
            instance = get_object_or_404(Event, pk=event_id)
        else:
            instance = Event(Users=request.user.username,
            start_time=datetime.now(),end_time=datetime.now())

        form = EventForm(request.POST or None, instance=instance)
        #request.user.username
        #form.instance.Users=request.user.username
        if request.POST and form.is_valid():
            if infer_time(form):
                form.save()
                return HttpResponseRedirect(reverse('cal:calendar'))
            else:
                contents="已被占用，请重新选择时间段进行预约"
                #return HttpResponseRedirect(reverse('cal:index'))#无法预约成功
                return render(request, 'cal/occupied.html', {'contents': contents})
        return render(request, 'cal/event.html', {'form': form})
    else:
        if request.method == "POST":
            form = AuthenticationForm(request, data=request.POST)
            if form.is_valid():
                username = form.cleaned_data.get('username')
                password = form.cleaned_data.get('password')
                user = authenticate(username=username, password=password)
                if user is not None:
                    login(request, user)
                    messages.info(request, f"You are now logged in as {username}.")
                    return redirect("cal:calendar")
                else:
                    messages.error(request, "Invalid username or password.")
            else:
                messages.error(request, "Invalid username or password.")
        form = AuthenticationForm()
        return render(request=request, template_name="cal/login.html", context={"login_form": form})

#获取当天已有的预约时间
def booked(day):
    all_users = Event.objects.all()
    befor_day=day-timedelta(days=1)
    after_day=day+timedelta(days=1)
#    select_user=all_users.filter(start_time > after_day).filter(start_time < befor_day)
    select_user=all_users.filter(start_time__lte=after_day.strftime("%Y-%m-%d")).filter(start_time__gte=befor_day.strftime("%Y-%m-%d"))
    #返回一系列时间值
    time_intervel=[[m.start_time,m.end_time]  for  m in select_user]
    return(time_intervel)


def infer_time(form):
    day_start=form.instance.start_time
    day_end=form.instance.end_time
    
    correct_date=day_start < day_end
    #先判断start
    time_intervel=booked(day_start)
    rs=[]
    for x,y in time_intervel:
        if x <= day_start <= y:
            rs.append(False)
        else:        
            if x <= day_end <= y:
                rs.append(False)
            else:
            #起始和终止均不再两者之间
                rs.append(True)
    if all(rs) and correct_date:
        return True
    else:
        return False



import pytz
def eventView(request, event_id=None):
    instance = Event()
    if event_id:
        instance = get_object_or_404(Event, pk=event_id)
    else:
        instance = Event()
    form = EventForm(None, instance=instance)
    username=form.instance.Users
    
    utc=pytz.UTC
    ctime = utc.localize(datetime.now()) 
    avaliable=ctime.replace(tzinfo=utc) < form.instance.start_time
    
    return render(request, 'cal/eventView.html', {'form': form,"username":username,"avaliable":avaliable})
 

def eventDelete(request):
    query = request.GET.get('Users')
    start_time = request.GET.get('start_time')
    #form= EventForm(request.GET)
    #x=form.instance.id
    print(Event.objects.all().filter(Users=query).filter(start_time=start_time))
    Event.objects.all().filter(Users=query).filter(start_time=start_time).delete()
    return HttpResponseRedirect(reverse('cal:event_new'))


''' 
def test(request, event_id=None):
    instance = ExampleForm()
    if event_id:
        instance = get_object_or_404(Event, pk=event_id)
    else:
        instance = ExampleForm()

    form = ExampleForm()
    if request.POST and form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('cal:test'))
    return render(request, 'cal/event.html', {'form': form})
'''
from django.shortcuts import  render, redirect
from .forms import NewUserForm#待定义forms,NewUserForm类
from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import AuthenticationForm
from .models import *
from django.shortcuts import  render, redirect
from django.contrib.auth import login
from django.contrib import messages
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import AuthenticationForm

from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from . import  models

def register_request(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)#需要定义NewUserForm
		if form.is_valid():
			user = form.save()
			login(request, user)
			messages.success(request, "Registration successful." )
			return redirect("cal:calendar")
		messages.error(request, "Unsuccessful registration. Invalid information.")
	form = NewUserForm()
	return render (request=request, template_name="cal/register.html", context={"register_form":form})


def login_request(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("cal:calendar")
            else:
                messages.error(request,"Invalid username or password.")
        else:
            messages.error(request,"Invalid username or password.")
    form = AuthenticationForm()
    return render(request=request, template_name="cal/login.html", context={"login_form":form})
 
from django.contrib.auth import login, authenticate, logout #add this
def logout_request(request):
    logout(request)
    message="You have successfully logged out ~"
    return render(request=request, template_name="cal/logout.html", context={"message":message})


#https://ordinarycoders.com/blog/article/django-password-reset 

#登录之后才能修改密码
def setPasswd(request):
    if request.user.is_authenticated:
        return render(request, 'cal/changepwd.html')
    else:
        if request.method == "POST":
            form = AuthenticationForm(request, data=request.POST)
            if form.is_valid():
                username = form.cleaned_data.get('username')
                password = form.cleaned_data.get('password')
                user = authenticate(username=username, password=password)
                if user is not None:
                    login(request, user)
                    messages.info(request, f"You are now logged in as {username}.")
                    return redirect("cal:setPasswd")
                else:
                    messages.error(request, "Invalid username or password.")
            else:
                messages.error(request, "Invalid username or password.")
        form = AuthenticationForm()
        return render(request=request, template_name="cal/login.html", context={"login_form": form})
   
#获取用户修改后的密码，并进行数据库更新
from django.contrib.auth.models import User
#https://stackoverflow.com/questions/35308015/how-to-update-django-auth-user-with-queryset
def updatePasswd(request):
    if request.user.is_authenticated:
        passwd = request.GET.get('Newpassword')
        username=request.user.username
        UsermodelUpdate=User.objects.get(username=username)
        UsermodelUpdate.set_password(passwd)
        UsermodelUpdate.save()
#        print(username+""+passwd)
        message="Your password has been reseted!"
        logout(request)

cal/templates/cal/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes">
  <!-- Bootstrap CSS -->
  <!--
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
    crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg"
    crossorigin="anonymous">
	-->
	<link rel="stylesheet" type="text/css" href="{% static 'cal/css/all.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'cal/css/bootstrap.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'cal/css/styles.css' %}">
  <title>预约系统</title>
</head>
<body>

  <h1 class="title">{% block title %}{% endblock %}</h1>
  <br>  

  {% block content %}
  {% endblock %}

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <!--
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
	-->

  {% block script %}
  {% endblock %}

</body>
</html>

cal/templates/cal/calendar.html
{% extends 'cal/base.html' %}

{% block title %}
仪器预约
{% endblock %}

{% block content %}
<div class="clearfix">
	<a class="btn btn-info left" href="{% url 'cal:calendar' %}?{{ prev_month }}"> Previous Month </a>
	<a class="btn btn-info left" href="{% url 'cal:calendar' %}?{{ next_month }}"> Next Month </a>
	
	{% if user.is_authenticated %}
      <a class="btn btn-info right" href="{% url 'cal:logout' %}"> Logout </a>
      {% else %}

      <a class="btn btn-info right" href="{% url 'cal:login' %}"> Login </a>
      {% endif %}
	
	<a class="btn btn-info right" href="{% url 'cal:event_new' %}"> New Event </a>
</div>

{{ calendar }}
{% endblock %}

cal/templates/cal/changepwd.html
{% extends "cal/base.html" %}
{% block content %}

<div id="search" style="text-align:center;">

<div style="width:15%;margin:0 auto">
<div style="text-align:left;"><strong>Reset Password</strong></div>

<form action="{% url 'cal:updatePasswd' %}" method="get">
  <div style="text-align:left;"><input name="Newpassword" type="password" value="abcd@1234" style="width:100%;"></div>
	<br />
  <div style="text-align:left;"><input type="submit" value="Update" style="width:80%;"></div>
  <br />
</form>


</div>


{% endblock %}

cal/templates/cal/event.html
{% extends 'cal/base.html' %}

{% block title %}
预约单
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'cal:calendar' %}"> Calendar </a>
</div>

{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ field.label }} <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

<form method="post">
  {% csrf_token %}
  <table class="form form-table">
    {{ form }}
    <tr><td colspan="2"><button type="submit" class="btn btn-info right"> Submit </button></td></tr>
  </table>
</form>
<div class="clearfix">
<br />
<br />
</div>
{% endblock %}

cal/templates/cal/eventView.html
{% extends 'cal/base.html' %}

{% block title %}
预约详情
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'cal:calendar' %}"> Calendar </a>
</div>


<form action="{% url 'cal:event_delete' %}" method="get">
{% csrf_token %}
  <table class="form form-table">
    {{ form }}
	{% if user.username == username %}
		{% if avaliable %}
			<tr><td colspan="2"><button type="submit" class="btn btn-info right"> Delete </button></td></tr>
		{% endif %}
	{% endif %}
  </table>
</form>



<div class="clearfix">
<br />
<br />
</div>
{% endblock %}

cal/templates/cal/login.html
{% extends "cal/base.html" %}

{% block title %}
登 录
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
<!--Login-->

<div class="clearfix" style="margin:auto">

  <h1>Login</h1>
  <form method="POST">
    {% csrf_token %}
    {{ login_form|crispy }}
	<br />
    <button class="btn btn-primary" type="submit">Login</button>
  </form>
</div>

<div class="clearfix">
<br />
<br />
</div>
<div class="clearfix">
<br />
<br />
</div>
{% endblock %}

cal/templates/cal/logout.html
{% extends "cal/base.html" %}

{% block content %}

<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'cal:calendar' %}"> Calendar </a>
</div>
<!--Login-->
<div class="container py-5">
<h3>{{ message }}</h3>
</div>

{% endblock %}

cal/templates/cal/occupied.html
{% extends 'cal/base.html' %}

{% block title %}
已被占用，请重新选择时间段进行预约
{% endblock %}

{% block content %}
<div class="clearfix">
  <a class="btn btn-info left" href="{% url 'cal:calendar' %}"> Calendar </a>
  <a class="btn btn-info right" href="{% url 'cal:event_new' %}"> New Event </a>
</div>


<div class="clearfix">
<br />
<br />
</div>
{% endblock %}

cal/templates/cal/register.html
{% extends "cal/base.html" %}

{% block content %}

{% load crispy_forms_tags %}

<!--Register-->
<div class="container py-5">
	<h1>Register</h1>
	<hr>
	<form method="POST">
		{% csrf_token %}
		{{ register_form|crispy }}
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	<p class="text-center">If you already have an account, <a href="/login">login</a> instead.</p>
</div>

{% endblock %}